### ISSUE TITLE
feature requests: change focus, delete a row

### ISSUE THREAD

**Issue by polgreen** [smowton/glorified-stopwatch#1]
## Change focus by clicking anywhere outside of the table? 
If i double click on a cell to change the value of the cell, and then want to exit that cell to start entering more times, hitting the enter button doesn't do anything until I click in the box that says "Competitor". I'd like to either be able to click anywhere outside the table to get the enter button to work again, or maybe be able to hit the enter button once to exit that cell and then once more to enter a time.

## Delete a row?
Can I delete a row in the table?

**Comment by smowton** [comment]
Both done in release 3
